/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoestore;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date; 
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MSI
 */

public class ShoesStoreUI extends javax.swing.JFrame {

    /**
     * Creates new form ShoesStoreUI
     */
    public ShoesStoreUI() {
        initComponents();
        getShoesID();
    }
    
    public DefaultTableModel DftTblModel_barang;
    public String SQL; 
    public String shoes_id[][] = new String[50][2];
    public int jml_shoes = 0;
    
    public static Connection getConnection() {
        Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/shoes_store";
        String user = "root";
        String password = "";
        try {
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            System.out.println(e);
        }
        return conn;
    }
    
    private void getShoesID(){
        // isi list ComboBox Shoes_ID dengan mengambil data dari tabel Shoes, field Shoes_ID
        Connection conn = getConnection();
        try {
            String id, nama;
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet res = stmt.executeQuery("SELECT * FROM `shoes` WHERE '1'");
            while (res.next()) {
                id = res.getString("Shoes_ID");
                nama = res.getString("Shoes_Name");
                shoes_id[jml_shoes][0] = id;
                shoes_id[jml_shoes][1] = nama;
                jml_shoes++;
            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        for(int i=0; i<jml_shoes; i++){
            shoesId.addItem(shoes_id[i][0]);
        }
    }
    
    public String TampilData(String vendorCode) {
        // Fungsi bantuan untuk mengambil data nama user berdasarkan ID dari database
        Connection conn = getConnection();
        String nama = null;
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM `customer` WHERE `Customer_ID` = '" + vendorCode + "'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                nama = res.getString("Customer_Name");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return nama;
    }
    
    private void calculateGrandTotal() {
        DefaultTableModel tblModel = (DefaultTableModel)txtSalesDetail.getModel();
        int GrandTotal = 0;
        for(int i=0; i < tblModel.getRowCount(); i++){
            GrandTotal += Integer.parseInt((String) tblModel.getValueAt(i, 4));
        }
        String strGrandTotal = String.valueOf(GrandTotal);
        if(GrandTotal == 0){
            txtGrandTotal.setText("Rp. 0");
        } else {
            txtGrandTotal.setText("Rp. "+strGrandTotal);
        }
    }
    
    public String formatDate(String str){
        String date = "", month = "", year = "";
        int iend = str.indexOf("-"); 
        if (iend != -1)
            date = str.substring(0 , iend);
        str = str.substring(iend+1, str.length());
        iend = str.indexOf("-"); 
        if (iend != -1)
            month = str.substring(0 , iend);
        year = str.substring(iend+1, str.length());
        if(date.length()==1)
            date = "0" + date;
        if(month.length()==1)
            month = "0" + month;
        String result = year + "-" + month + "-" + date;
        return result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSales_ID = new javax.swing.JTextField();
        txtSales_Date = new javax.swing.JTextField();
        txtCustomer_ID = new javax.swing.JTextField();
        txtCustomer_RefNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtViewCustomer_Nama = new javax.swing.JTextField();
        txtGrandTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        shoesId = new javax.swing.JComboBox<>();
        txtShoes_Name = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalesDetail = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 176, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Shoes Store");
        jLabel1.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(146, 208, 80));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Purchase ID");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Kode Vendor");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Vendor RefNo");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText(":");

        txtSales_ID.setText(" ");

        jButton1.setText("View");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtViewCustomer_Nama.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSales_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtSales_Date)
                            .addComponent(txtCustomer_ID)
                            .addComponent(txtCustomer_RefNo))
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCustomer_Nama))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtSales_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtSales_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtCustomer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(txtViewCustomer_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtCustomer_RefNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setText("Rp. 0");

        jPanel4.setBackground(new java.awt.Color(55, 86, 35));

        shoesId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        shoesId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shoesIdItemStateChanged(evt);
            }
        });

        txtShoes_Name.setEditable(false);

        jButton2.setText("Tambah item");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Hapus item");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Shoes_ID");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama Sepatu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantity");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Price");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(88, 88, 88)
                .addComponent(jLabel11)
                .addGap(80, 80, 80)
                .addComponent(jLabel12)
                .addGap(58, 58, 58)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(shoesId, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtShoes_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shoesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShoes_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Sales DETAIL");

        txtSalesDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Sepatu", "Quantity", "Price", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(txtSalesDetail);

        jButton4.setText("Simpan");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Keluar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Menampilkan data nama user berdasarkan input ID, ketika klik tombol view
        JFrame jFrame = new JFrame();
        String vendorCode = txtCustomer_ID.getText();
        if("".equals(vendorCode)){
            JOptionPane.showMessageDialog(jFrame, "Mohon isi field Customer ID");
        }
        else {
            String outputName = TampilData(vendorCode);
            if(outputName == null){
                txtCustomer_ID.setText("");
                txtViewCustomer_Nama.setText("");
                JOptionPane.showMessageDialog(jFrame, "Customer Belum Terdaftar!");
            } else {
                txtViewCustomer_Nama.setText(outputName);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void shoesIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shoesIdItemStateChanged
        // action ketika ComboBox Shoes_ID value nya berubah
        String id = (String) shoesId.getSelectedItem();
        if(!("-".equals(id))){
            for(int i=0; i<jml_shoes; i++){
                if(shoes_id[i][0].equals(id))
                    txtShoes_Name.setText(shoes_id[i][1]);
            } 
        } else {
            txtShoes_Name.setText("");
        }

    }//GEN-LAST:event_shoesIdItemStateChanged

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        //exit
        dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        // action ketika tombol "Tambah Item" diklik
        
        if(txtQuantity.getText().equals("")||shoesId.getSelectedItem().equals("-")||txtPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Semua field!");
        } else {
            String id = (String) shoesId.getSelectedItem();
            String name = txtShoes_Name.getText();
            String quantity = txtQuantity.getText();
            String price = txtPrice.getText();
            String sub_total;
            int qty , prc;
            
            // validasi input integer untuk field quantity dan price
            try {
                qty = Integer.parseInt(quantity);
                prc = Integer.parseInt(price);
                int subtotal = qty * prc;
                sub_total = String.valueOf(subtotal);
                String data[] = {id,name,quantity,price,sub_total};
                DefaultTableModel tblModel = (DefaultTableModel)txtSalesDetail.getModel();
                tblModel.addRow(data);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantity atau Price tidak valid!\n(wrong number format)");
                txtQuantity.setText("");
                txtPrice.setText("");
            }
            
            
        }
        calculateGrandTotal();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        // action ketika tombol "Hapus" diklik
        DefaultTableModel tblModel = (DefaultTableModel)txtSalesDetail.getModel();
        if(txtSalesDetail.getSelectedRowCount()==1){
            tblModel.removeRow(txtSalesDetail.getSelectedRow());
        } else {
            if(txtSalesDetail.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tabel Kosong");
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            }
        }
        calculateGrandTotal();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        // action ketika tombol "simpan" diklik
        if(txtSales_ID.getText().equals("")||txtSales_Date.getText().equals("")||txtCustomer_ID.getText().equals("")||txtCustomer_RefNo.getText().equals("")||txtViewCustomer_Nama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Semua field!");
        } else {
            if(txtSalesDetail.getRowCount()==0) {
                JOptionPane.showMessageDialog(this, "Tabel Kosong!\nHarap Isi data terlebih dahulu!");
            } else {
                String id_sales = txtSales_ID.getText().replace(" ", "");
                String id_cust = txtCustomer_ID.getText().replace(" ", "");
                String ref_cust = txtCustomer_RefNo.getText();
                String date = formatDate(txtSales_Date.getText());
                Date date_formatted;
                // cek format tanggal 
                try {
                    date_formatted = Date.valueOf(date);
                    
                    // insert dan update data ke db
                    try {
                        // insert data ke tabel sales
                        Connection conn = getConnection();
                        String query = "INSERT INTO `sales`(`Sales_ID`, `Sales_Date`, `Customer_ID`, `Customer_RefNo`) VALUES (?,?,?,?)";
                        PreparedStatement preparedStmt = conn.prepareStatement(query);
                        preparedStmt.setInt(1, Integer.parseInt(id_sales));
                        preparedStmt.setDate(2, date_formatted);
                        preparedStmt.setInt(3, Integer.parseInt(id_cust));
                        preparedStmt.setString(4, ref_cust);
                        preparedStmt.execute();
                        
                        // insert data ke tabel sales_detail
                        try {
                            DefaultTableModel tblModel = (DefaultTableModel)txtSalesDetail.getModel();
                            for(int i=0; i < tblModel.getRowCount(); i++){
                                // insert data ke tabel sales_detail
                                String shoes_id = (String) tblModel.getValueAt(i, 0);
                                String qty = (String) tblModel.getValueAt(i, 2);
                                String price = (String) tblModel.getValueAt(i, 3);

                                query = "INSERT INTO `sales_detail`(`Sales_ID`, `Shoes_ID`, `Quantity`, `Price`) VALUES (?,?,?,?)";
                                PreparedStatement preparedStmtInsert = conn.prepareStatement(query);
                                preparedStmtInsert = conn.prepareStatement(query);
                                preparedStmtInsert.setInt(1, Integer.parseInt(id_sales));
                                preparedStmtInsert.setInt(2, Integer.parseInt(shoes_id));
                                preparedStmtInsert.setInt(3, Integer.parseInt(qty));
                                preparedStmtInsert.setInt(4, Integer.parseInt(price));
                                preparedStmtInsert.execute();

                                // update stock
                                int stock = 0;
                                java.sql.Statement stmt = conn.createStatement();
                                query = "SELECT * FROM `shoes` WHERE Shoes_ID = '"+Integer.parseInt(shoes_id)+"';";
                                java.sql.ResultSet res = stmt.executeQuery(query);
                                while (res.next()) {
                                    stock = Integer.parseInt(res.getString("Stock"));
                                }

                                // menggunakan rumus stock = stock - quantity
                                stock = stock - Integer.parseInt(qty);
                                query = "UPDATE `shoes` SET `Stock`=? WHERE Shoes_ID = ?";
                                PreparedStatement preparedStmtUpdate = conn.prepareStatement(query);
                                preparedStmtUpdate = conn.prepareStatement(query);
                                preparedStmtUpdate.setInt(1, stock);
                                preparedStmtUpdate.setInt(2, Integer.parseInt(shoes_id));
                                preparedStmtUpdate.executeUpdate();
                            }
                            // tampilkan pesan berhasil
                            JOptionPane.showMessageDialog(this, "Tambah Data Berhasil!!");
                            // kosongkan form
                            txtSales_ID.setText("");
                            txtSales_Date.setText("");
                            txtCustomer_ID.setText("");
                            txtViewCustomer_Nama.setText("");
                            txtCustomer_RefNo.setText("");
                            txtGrandTotal.setText("Rp. 0");
                            shoesId.setSelectedIndex(0);
                            txtShoes_Name.setText("");
                            txtQuantity.setText("");
                            txtPrice.setText("");
                            for(int i=0; i<=txtSalesDetail.getRowCount(); i++){
                                tblModel.removeRow(0);
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(this, "ERROR! : Insert Data ke tabel 'sales_detail'\n" + e.getMessage());
                        }
                        
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "ERROR! : Insert Data ke tabel 'sales'\n" + e.getMessage());
                    }
                } catch(IllegalArgumentException e) {
                    JOptionPane.showMessageDialog(this, "ERROR!\nDate Format Invalid");
                }
                
            }
        }
    }//GEN-LAST:event_jButton4MouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoesStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoesStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoesStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoesStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoesStoreUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> shoesId;
    private javax.swing.JTextField txtCustomer_ID;
    private javax.swing.JTextField txtCustomer_RefNo;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTable txtSalesDetail;
    private javax.swing.JTextField txtSales_Date;
    private javax.swing.JTextField txtSales_ID;
    private javax.swing.JTextField txtShoes_Name;
    private javax.swing.JTextField txtViewCustomer_Nama;
    // End of variables declaration//GEN-END:variables
}
